[package]
name = "mongodb_json_loader"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "load_json"
path = "load_json.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0.105", features = ["derive"] }
serde_json = "1.0.50"
mongodb = "2.2.0"
